name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# 添加并发控制 - 防止多个部署冲突
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: rm -rf public && hugo --minify --cleanDestinationDir
      
      - name: List contents of public dir
        run: ls -la public
        
      # 使用 GitHub 官方的上传页面工件动作
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build  # 确保在 build 作业完成后运行
    runs-on: ubuntu-latest
    permissions:
      pages: write      # 必须要有 pages 写入权限
      id-token: write   # 必须要有 id-token 权限
    
    # 配置环境，这是触发页面更新的关键
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      # 使用 GitHub 官方的部署页面动作
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4